gh_actions/attach_plan_to_pr/README.md
gh_actions/attach_plan_to_pr/action.yml

Sometimes, legitimate PRs get lots of updates and it results in comment spam. This is an attempt to trim down on that spam.

Add a way to ignore plan for normal deployments

---

gh_actions/attach_plan_to_pr/README.md
gh_actions/attach_plan_to_pr/action.yml

`github.event.after` only exists for PRs.

Bugfix - use the sha

---

gh_actions/attach_plan_to_pr/README.md
gh_actions/attach_plan_to_pr/action.yml

This is to fix a bug where the text artifact wouldn't save when the plan didn't go to a PR.

Ensure the plan text is in a consistent place.

---

gh_actions/attach_plan_to_pr/action.yml

With large plans, the `echo` command can overflow the command-line buffer. Use `tee` instead to redirect to a file.

Fix bash command overflow with large plans.

---

gh_actions/attach_plan_to_pr/action.yml

Facing issues in not outputting the plan in Pr when add_plan_to_pr set to 'false' in the PR. 
Adding check inputs.add_plan_to_pr == 'true' for plan output block.
Please see
https://github.com/actions/runner/issues/1483

Boolean check inputs.add_plan_to_pr == 'true' for plan o/p.

---

docs/modules/kms_secrets.md
modules/kms_secrets/main.tf
modules/kms_secrets/variables.tf

A new argument to the `kms_secrets` module allows anyone to easily save the secrets into SSM Parameter Store.

Allow secrets to be saved to SSM Parameter Store

---

docs/modules/kms_secrets.md
modules/kms_secrets/main.tf
modules/kms_secrets/variables.tf

- Update documentation to move `secretsmanager_key` and `ssm_parameter_prefix` as top level variables.
- Fix bug that uses default aws managed ssm key.

fix(modules/kms_secrets): use custom kms for ssm params

---

docs/README.md
docs/modules/datadog_aws_integration.md
modules/datadog_aws_integration/conf.tf
modules/datadog_aws_integration/main.tf
modules/datadog_aws_integration/output.tf
modules/datadog_aws_integration/variables.tf

The purpose of this plugin is to help project get jump-started integrating with Datadog.
Easy-to-read documentation here: https://github.com/RSS-Engineering/terraform/blob/datadog/docs/README.md and https://github.com/RSS-Engineering/terraform/blob/datadog/docs/modules/datadog_aws_integration.md

Datadog AWS Integration

---

docs/modules/api_gateway.md
modules/api_gateway/main.tf

We needed to be able to specify a host header to the proxy endpoint. This allows for that.

Support static header values for proxy_url redirects

---

docs/modules/api_gateway.md
modules/api_gateway/main.tf

The default authorizer type is `TOKEN`, but that only sends the token value specified by `identity_source` to the authorizer Lambda function, whereas `REQUEST` will send the entire request object, which might be helpful in certain cases.

Allow the authorizer type to be specified

---

docs/index.html

Relative paths in markdown do not work w/ the default docsify settings.
e.g. currently published docs (via #31) @ https://rss-engineering.github.io/terraform/#/modules/security_hub have a relative link to another doc in the same folder:
```md
This should be provisioned together with the [guardduty](./guardduty.md) product.
```
When rendered by docsify, it results in a non-existent destination:
```html
- /#/./guardduty
```
Setting `relativePath: true` will correctly render the link and preserve the ability to navigate `*.md` docs in the Github UI:
```diff
- /#/./guardduty
+/#/modules/guardduty
```
See https://docsify.js.org/#/configuration?id=relativepath

Use relative paths for generated docsify links

---

docs/modules/api_gateway.md
modules/api_gateway/main.tf

This isn't referenced anywhere and causes an error if there isn't a route for `/`

remove unused local which causes errors when there's no root route

---

modules/api_gateway/main.tf

Hashing just the `id` is a bit simpler and more predictable but also misses out on a lot of potential changes which should probably be triggering a deployment. [Docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_deployment#terraform-resources) indicate that hashing the entire resource is a valid approach here.

Hash full resources for apigw redeployment

---

modules/api_gateway/main.tf
modules/api_gateway/versions.tf

At one point there was a bug that qualified the lambda invoke arn unnecessarily but that has been fixed. The workaround is making it so it's impossible to use a qualified arn for the routes. Being able to call a specific version of a lambda could be important - especially when combined with the `deployments` feature of apigw.

Remove workaround and allow qualified arns to be used

---

docs/modules/api_gateway.md
modules/api_gateway/main.tf
modules/api_gateway/output.tf
modules/api_gateway/variables.tf

The built-in management doesn't handle versioned lambdas, and I'm not 100% sure this is the final fix for this problem but the permissions need to be reapplied whenever a new version is published in order for APIGW to have permission to call the newly deployed lambda. Since we don't have direct access to the `aws_lambda_function` resource in the module it's difficult to trigger updates like is shown in the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission#with-replace_triggered_by-lifecycle-configuration). This seems like something that shouldn't be the responsibility of this module anyway, so I'm adding a flag to opt-out of the behavior for backwards compatibility.

feat: allow consumer to self-manage lambda permissions

---

docs/modules/api_gateway.md
modules/api_gateway/main.tf
modules/api_gateway/variables.tf

The idea here is that instead of adding permissions on each lambda (and potentially each _version_ of each lambda) we should just grant permissions to the role assumed by APIGW when calling the lambdas, and use wildcards for versioned lambdas. This way, whenever we add a new version of a lambda the APIGW will already have access to invoke it without any permissions changes required.
If we manage invoke permissions using the `aws_lambda_permission` resource, terraform will destroy the permission required for the currently running deployment before the new deployment is created so there will be a moment when traffic is hitting the old lambda but the gateway does not have permission to invoke the old lambda anymore causing a disruption. This also means that rolling back a deployment would …

feat: grant permission to invoke lambdas by policy

---

gh_actions/attach_plan_to_pr/action.yml

Large plans were overloading the ENVVAR space and the step was failing. This removes unnecessary state update text and runs the plan through a file.

Simplify plan text

---

modules/api_gateway/variables.tf

Fix this error in mass-comm
```
│ Error: Invalid type specification
│ 
│   on .terraform/modules/main.api_gateway.api_gateway/modules/api_gateway/variables.tf line 72, in variable "binary_media_types":
│   72:   type    = list()
│ 
│ The list type constructor requires one argument specifying the element
│ type.
```

fix(*): fix binary media types var

---

modules/security_hub/main.tf

In order to use audit manager effectively for our PCI compliance, we also need to enable the PCI standard in security hub

feat: enable PCI v4.0.1 security hub standard

---

modules/security_hub/main.tf

We're moving towards centralized security hub and this entire module probably won't be necessary anymore once that happens. Not all accounts were updated to use a recent enough version of the module to even enable this in the first place, and I'm running into issues where it is being enabled. The standard takes a while to provision, and it's causing terraform to time out.
> Error: waiting for Security Hub Standards Subscription (arn:aws:securityhub:us-east-1:152267171281:subscription/pci-dss/v/4.0.1) create: timeout while waiting for state to become 'READY, INCOMPLETE' (last state: 'PENDING', timeout: 3m0s)
I'm just going to remove it for now, and it can always be manually toggled back on if desired.

chore: disable mostly unused pci4 standard

---

modules/security_hub/main.tf

Some consumers (like janus-infra) may have an older version of the module which still had PCI enabled. This adds an additional removed block to remove that from state if it exists.

fix: add removed block for the pci subscription

---

docs/modules/s3_bucket.md
modules/s3_bucket/main.tf
modules/s3_bucket/variables.tf

**JIRA:** https://rackspace.atlassian.net/browse/RESUI-1367
**Description:**
**Support passing through tags to S3 bucket.**
Note: The plan is to invoke the S3 bucket creation module in this repo from our GitHub reusable workflow (in the .github repo). This workflow is used by the micro UI starter kit template to create a private bucket with OAC instead of a public S3 bucket.

Support passing through tags to S3 bucket
